version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: wallet_postgres
    environment:
      POSTGRES_USER: WalletDbUser
      POSTGRES_PASSWORD: WalletDbUserPass
      POSTGRES_DB: WalletRestDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wallet_network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.1
    container_name: wallet_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - wallet_network

  kafka:
    image: confluentinc/cp-kafka:7.4.1
    container_name: wallet_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - wallet_network

  app:
    build: .
    container_name: wallet_app
    depends_on:
      - postgres
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/WalletRestDb
      SPRING_DATASOURCE_USERNAME: WalletDbUser
      SPRING_DATASOURCE_PASSWORD: WalletDbUserPass
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8080:8080"
    networks:
      - wallet_network

volumes:
  postgres_data:

networks:
  wallet_network: